-- Insert mock services
insert into public.services (name, description, category, publisher_address, image_url, features, webhook_url, webhook_events, custom_fields, monthly_price, quarterly_price, yearly_price, auto_renewal, subscribers_count) values
(
  'AI Content Generator',
  'Advanced AI-powered content generation service for blogs, social media, and marketing materials',
  'AI & ML',
  '7xKXtg2CW3v9tefJVY5KqBb7wH4ANYx8aZLPvJ9Eqyc',
  '/placeholder.svg?height=400&width=600',
  ARRAY['GPT-4 Integration', 'Multi-language Support', 'SEO Optimization', 'Plagiarism Check'],
  'https://api.example.com/ai-content/webhook',
  ARRAY['subscription_activated', 'content.generated', 'usage.limit'],
  '[{"name": "email", "type": "email", "required": true}, {"name": "company", "type": "text", "required": false}]'::jsonb,
  29.99,
  79.99,
  299.99,
  true,
  1234
),
(
  'Blockchain Analytics Pro',
  'Real-time blockchain data analytics and insights for traders and investors',
  'Data & Analytics',
  '9yMZvh3DX4w0ufgKWZ6LrCc8xI5BOZy9bAMQwK0Frzd',
  '/placeholder.svg?height=400&width=600',
  ARRAY['Real-time Data', 'Custom Alerts', 'Portfolio Tracking', 'API Access'],
  'https://api.example.com/analytics/webhook',
  ARRAY['subscription_activated', 'alert.triggered', 'data.updated'],
  '[{"name": "telegram_username", "type": "text", "required": false}, {"name": "notification_email", "type": "email", "required": false}]'::jsonb,
  49.99,
  134.99,
  499.99,
  true,
  856
),
(
  'NFT Marketplace API',
  'Complete API solution for building NFT marketplaces on Solana',
  'NFT',
  '2aNbwi4EY5x1vghLXa7MsDd9yJ6CPAz0cBNRxL1Gsae',
  '/placeholder.svg?height=400&width=600',
  ARRAY['Minting Support', 'Royalty Management', 'Metadata Storage', 'Wallet Integration'],
  'https://api.example.com/nft/webhook',
  ARRAY['subscription_activated', 'nft.minted', 'nft.sold', 'nft.transferred'],
  '[{"name": "wallet_address", "type": "text", "required": true}, {"name": "collection_name", "type": "text", "required": false}]'::jsonb,
  99.99,
  269.99,
  999.99,
  true,
  542
),
(
  'DeFi Yield Optimizer',
  'Automated yield farming and liquidity optimization across multiple DeFi protocols',
  'DeFi',
  '5cPdxj5FZ6y2wihMYb8NtEe0zK7DQBa1dCOSyM2Htbf',
  '/placeholder.svg?height=400&width=600',
  ARRAY['Auto-compounding', 'Risk Assessment', 'Multi-protocol Support', 'Gas Optimization'],
  'https://api.example.com/defi/webhook',
  ARRAY['subscription_activated', 'yield.harvested', 'position.rebalanced'],
  '[{"name": "risk_tolerance", "type": "text", "required": false}, {"name": "investment_amount", "type": "number", "required": false}]'::jsonb,
  79.99,
  214.99,
  799.99,
  true,
  723
),
(
  'Smart Contract Auditor',
  'Automated security auditing and vulnerability detection for Solana smart contracts',
  'Security',
  '8eRfyk6GA7z3xjiNZc9OuFf1aL8ERCb2eDPTzN3Iucg',
  '/placeholder.svg?height=400&width=600',
  ARRAY['Automated Scanning', 'Vulnerability Reports', 'Best Practices Check', 'Continuous Monitoring'],
  'https://api.example.com/audit/webhook',
  ARRAY['subscription_activated', 'audit.completed', 'vulnerability.found'],
  '[{"name": "contract_address", "type": "text", "required": true}, {"name": "contact_email", "type": "email", "required": true}]'::jsonb,
  149.99,
  404.99,
  1499.99,
  true,
  389
),
(
  'Social Token Platform',
  'Launch and manage your own social tokens with built-in governance and rewards',
  'Social',
  '4dQgzk7HB8a4yjkOad0PvGg2bM9FSDb3fEQUaO4Jvdh',
  '/placeholder.svg?height=400&width=600',
  ARRAY['Token Creation', 'Governance Tools', 'Reward Distribution', 'Community Dashboard'],
  'https://api.example.com/social/webhook',
  ARRAY['subscription_activated', 'token.created', 'vote.cast', 'reward.distributed'],
  '[{"name": "social_handle", "type": "text", "required": false}, {"name": "token_symbol", "type": "text", "required": false}]'::jsonb,
  39.99,
  107.99,
  399.99,
  true,
  612
);
